package deploymentTool;

import java.io.IOException;
import java.util.Map;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;

import PASYS_Metamodel.pasys.PasysPackage;

/**
 * MDE tool for deleting the configuration files and scripts
 * generated by the deployment tool
 * For the moment, it does not stop the servers started
 * @author ISTR
 *
 */
public class DeploymentCleanTool {

	public static void main(String[] args) {

		String pabmPath = args[0];

		ResourceSet resourceSet = new ResourceSetImpl();

		Map packageRegistry = resourceSet.getPackageRegistry();
		packageRegistry.put(PasysPackage.eNS_URI, PasysPackage.eINSTANCE);

		Map<String, Object> extensionFactoryMap = Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap();
		extensionFactoryMap.put("xmi", new XMIResourceFactoryImpl());

		URI pabmUri = URI.createFileURI(pabmPath);
		Resource pabmResource = (Resource) resourceSet.createResource(pabmUri);
		try {
			pabmResource.load(null);
			EcoreUtil.resolveAll(pabmResource);

			PASYS_Metamodel.pasys.ComputationalSystem system = (PASYS_Metamodel.pasys.ComputationalSystem) pabmResource
					.getContents().get(0);
			
			// Triggers the cleaning process
			system.cleanDeployment();
			
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

}
