# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 1
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.48:9091']
  - job_name: 5
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.47:9091']
  - job_name: 9
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.52:9091']
  - job_name: 13
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.51:12000']
  - job_name: 17
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.38:9091']
  - job_name: 25
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.44:9091']
  - job_name: 33
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.49:9091']
  - job_name: 21
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.54:9091']
  - job_name: 29
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.63:9091']
  - job_name: 37
    scrape_interval: 3600000s
    static_configs:
      - targets: ['172.31.16.53:9091']
  - job_name: DailyConsumptionLoggingMeter
    scrape_interval: 2592000000s
    static_configs:
      - targets: ['172.31.16.49:12010', '172.31.16.53:12010', '172.31.16.54:12010', '172.31.16.44:12010', '172.31.16.63:12010', '172.31.16.38:12010']
  - job_name: 246
    scrape_interval: 2592000000s
    static_configs:
      - targets: ['172.31.16.49:12003', '172.31.16.53:12003', '172.31.16.54:12003', '172.31.16.44:12003', '172.31.16.63:12003', '172.31.16.38:12003']

